form/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', views.index),
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/detail/', views.detail, name="detail"),
    path('<int:id>/delete', views.delete, name="delete"),
    path('<int:id>/update', views.update, name="update"),

    path('create-model-form/', views.create_model_form, name="create_model_form"),
    path('<int:id>/update-model-form/',
         views.update_model_form, name="update_model_form"),

    path('<int:id>/comments/create', views.comment_create, name="comment_create"),
]

movies/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    class Meta:
        ordering = ('-id',)

movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.Form):
    title = forms.CharField(max_length=100)
    title_en = forms.CharField(
        max_length=100,
        label="영문제목",
        widget=forms.TextInput(
            attrs={
                'placeholder': '영문제목을 입력해주세요'
            }
        )
    )
    audience = forms.IntegerField()
    open_date = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date'}))
    genre = forms.CharField(max_length=100)
    watch_grade = forms.CharField(max_length=100)
    score = forms.FloatField()
    poster_url = forms.CharField(widget=forms.Textarea)
    description = forms.CharField(widget=forms.Textarea)


class MovieModelForm(forms.ModelForm):
    open_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    datetime = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Movie
        fields = '__all__'


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
# 모델폼을 만들어서 이름은 comment 내용은 contents
# views에 create_model_form

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MovieForm, MovieModelForm, CommentModelForm
from IPython import embed
from .models import Movie
# Create your views here.


def index(request):
    movies = Movie.objects.all().order_by('-id')
    context = {
        'movies': movies
    }
    return render(request, 'index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = Movie()
            movie.title = form.cleaned_data.get('title')
            movie.title_en = form.cleaned_data.get('title_en')
            movie.audience = form.cleaned_data.get('audience')
            movie.open_date = form.cleaned_data.get('open_date')
            movie.genre = form.cleaned_data.get('genre')
            movie.watch_grade = form.cleaned_data.get('watch_grade')
            movie.score = form.cleaned_data.get('score')
            movie.poster_url = form.cleaned_data.get('poster_url')
            movie.description = form.cleaned_data.get('description')
            movie.save()

            return redirect('movies:index')
        else:
            pass
    else:
        form = MovieForm()
    context = {
        'form': form
    }
    return render(request, 'form.html', context)


def detail(request, id):
    # movie = Movie.objects.get(id=id)
    movie = get_object_or_404(Movie, id=id)
    comment_form = CommentModelForm()
    context = {
        "movie": movie,
        'comment_form': comment_form
    }
    return render(request, 'detail.html', context)


def delete(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect("movies:detail")


def update(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie.title = form.cleaned_data.get('title')
            movie.title_en = form.cleaned_data.get('title_en')
            movie.audience = form.cleaned_data.get('audience')
            movie.open_date = form.cleaned_data.get('open_date')
            movie.genre = form.cleaned_data.get('genre')
            movie.watch_grade = form.cleaned_data.get('watch_grade')
            movie.score = form.cleaned_data.get('score')
            movie.poster_url = form.cleaned_data.get('poster_url')
            movie.description = form.cleaned_data.get('description')
            movie.save()
            return redirect('movies:detail', id)
    else:
        form = MovieForm(initial=movie.__dict__)
    context = {
        'form': form
    }
    return render(request, 'form.html', context)


def create_model_form(request):
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.id)

    else:
        form = MovieModelForm()
    context = {
        'form': form
    }
    return render(request, 'form.html', context)


def update_model_form(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', id)
    else:
        form = MovieModelForm(instance=movie)
    context = {
        'form': form
    }
    return render(request, 'form.html', context)


def comment_model_form(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.id)
    else:
        form = MovieModelForm()
    context = {
        'form': form
    }
    return render(request, 'form.html', context)


def comment_create(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.movie = movie
            comment.save()
            return redirect('movies:detail', id)
        else:
            pass
    else:
        pass

movies/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Doc</title>
  {% bootstrap_css %}
</head>
<body>
  <a href="{% url 'movies:index' %}">홈</a>
  <a href="{% url 'movies:create' %}">글쓰기</a>
  <a href="{% url 'movies:create_model_form' %}">글쓰기(모델폼)</a>
  <div class="container">
  {% block body %}
  {% endblock %}
  {% bootstrap_javascript jquery='full' %}
  </div>
</body>
</html>

movies/templates/detail.html
{% extends 'base.html' %}
{% block body %}
  <h1>{{movie.title}}</h1>
  <form action="{% url 'movies:delete' movie.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제(post)">
  </form>
  <a href="{% url 'movies:update' movie.id %}">수정</a>
  <a href="{% url 'movies:update_model_form' movie.id %}">수정(모델폼)</a>
  
  <hr>

  <form action="{% url 'movies:comment_create' movie.id %}" method="post">
    {% csrf_token %}
    {{comment_form.as_p}}
    <input type="submit">
  </form>
  
  {% for comment in movie.comment_set.all %}
    <p>{{comment.content}}</p>
  {% endfor %}
{% endblock %}

movies/templates/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  {% if request.resolver_match.url_name == "create_model_form" %}
    <h1>create</h1>
  {% else %}
    <h1>update</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="제출" %}
    {% endbuttons %}
  </form>
{% endblock %}

movies/templates/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>index</h1>
    {% for movie in movies%}
      <div>
      {{movie.title}}
      {{movie.title_en}}
      {{movie.audience}}
      {{movie.open_date}}
      {{movie.genre}}
      {{movie.watch_grade}}
      {{movie.score}}
      {{movie.poster_url}}
      {{movie.description}}
      <a href="{% url 'movies:detail' movie.id %}">자세히보기</a>
      </div>
    {% endfor %}
{% endblock %}

movies/templates/update.html
{% extends 'base.html' %}
{% block body %}
  {{form.as_p}}
{% endblock %}